services:
  - type: web
    name: fidelizasucre
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fidelizasucre-db
          property: connectionString

databases:
  - name: fidelizasucre-db
    plan: free
